# Optimizing Neural Network Hyperparameters

We will consider an Image Recognition problem with MNIST dataset (28 x 28 images). The MNIST dataset has a training set of 60,000 images and a test set of 10,000 images. The digits have been sized-normalized and centered in a fixed-size image.
It is a good database for people who want to try learning techniques and pattern recognition methods on real-world data while spending minimal efforts on preprocessing and formatting.

In this Notebook you will follow two different approaches to tune the hyperparameters:
- "Trial and Error" approach;
- "Grid Search" Hyperparameter optimization with Scikit-Learn wrapper;

### Data Preparation

In [5]:
from keras.datasets import mnist



In [9]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
# train_x, train_y, test_x, test_y
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

11493376/11490434 [==============================] - 15s 1us/step


In [16]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [17]:
split_size = int(train_images.shape[0]*0.7)
print(split_size)
train_images, val_images = train_images[:split_size], train_images[split_size:]
train_labels, val_labels = train_labels[:split_size], train_labels[split_size:]

29399


### Building the Model

Build a neural network with 3 layers, input, hidden and output:
- Dense layer with 50 hidden units and an appropriate activation function;
- Dense layer with 10 output units and an appropriate activation function;

First we define some useful parameters:

In [19]:
# define vars
input_num_units = 784
hidden_num_units = 50
output_num_units = 10

epochs = 5
batch_size = 128

** Import Keras packages that you think may need.**

In [25]:
import numpy as np
from keras import models
from keras import layers

** Create the model as described above. **

In [26]:
model = models.Sequential()
model.add(layers.Dense(input_num_units, activation='relu'))
model.add(layers.Dense(hidden_num_units, activation='relu'))
model.add(layers.Dense(output_num_units, activation='softmax'))

** Configure the model with an optimizer and an appropriate loss function. **

In [27]:
model.compile(optimizer='adam',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

** Train the model (also with the validation set). **

In [28]:
model.fit(train_images, train_labels, batch_size = 128, epochs = 5, validation_data = (val_images, val_labels))

ValueError: Error when checking target: expected dense_6 to have 2 dimensions, but got array with shape (29399, 10, 2, 2, 2)

### Model Evaluation

** Test the model: get some prediction and evaluate the model. **

In [29]:
index = model.predict(test_images[:10])

In [30]:
print(test_labels[0:10])

[[[[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[0. 1.]
    [1. 0.]]

   [[1. 0.]
    [0. 1.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]]



 [[[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[0. 1.]
    [1. 0.]]

   [[1. 0.]
    [0. 1.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[1. 0.]
    [0. 1.]]



In [31]:
for i in range(0, 10):
    print(np.argmax(index[i]))
    

7
3
3
9
9
3
9
9
6
6


Let's try to improve it by tuning some Hyperparameters.

### Hyperparameters Optimization - Trial and Error

Some important parameters to look out while optimizing neural networks are:
- Type of architecture;
- Number of layers;
- Number of neurons per layer;
- Regularization parameters;
- Learning rate;
- Type of optimization/backpropagation technique;
- Dropout rate;
- Weight sharing;

Now repeat all the previous steps (train, test etc..) but tuning the following parameters:
1. Make the model "wide": Increase the number of neurons in the hidden layer; 
2. Make the model "deep": Increase the number of hidden layers neurons each;
3. Dropout to deal with Overfitting;
4. Increase Epochs to 50;
5. Both "wide" and "deep": more hidden layers, each with more than 50 neurons

After every step, analyse your results and draw some conclusions.

### 1. Make the model "wide": increase number of neurons in the hidden layer.

** Define the new variables. **

In [19]:
# define vars
input_num_units = 784
hidden_num_units = 256
output_num_units = 10

epochs = 5
batch_size = 128

** Build the network. **

In [20]:
model = models.Sequential()
model.add(layers.Dense(input_num_units, activation='relu'))
model.add(layers.Dense(hidden_num_units, activation='relu'))
model.add(layers.Dense(output_num_units, activation='softmax'))

** Configure the network. **

In [21]:
model.compile(optimizer='adam',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

** Train the network. **

In [22]:
model.fit(train_images, train_labels, batch_size = 128, epochs = 5, validation_data = (val_images, val_labels))

Train on 42000 samples, validate on 18000 samples
Epoch 1/5
42000/42000 [==============================] - 5s 114us/step - loss: 0.2494 - acc: 0.9260 - val_loss: 0.1432 - val_acc: 0.9557
Epoch 2/5
42000/42000 [==============================] - 5s 107us/step - loss: 0.0938 - acc: 0.9715 - val_loss: 0.1009 - val_acc: 0.9699
Epoch 3/5
42000/42000 [==============================] - 5s 108us/step - loss: 0.0576 - acc: 0.9819 - val_loss: 0.0887 - val_acc: 0.9733
Epoch 4/5
42000/42000 [==============================] - 5s 112us/step - loss: 0.0379 - acc: 0.9883 - val_loss: 0.0998 - val_acc: 0.9714
Epoch 5/5
42000/42000 [==============================] - 5s 110us/step - loss: 0.0237 - acc: 0.9926 - val_loss: 0.0935 - val_acc: 0.9746


In [ ]:
Markdown
no of iterations * epoch = batch_size

No major change in loss and accuracy (training and validation)

Considerations: what can you notice from these results? Is your model performing better than before?

### 2. Make the model "deep": Increase the number of hidden layers.

** Define the new variables. **

In [29]:
# define vars
input_num_units = 784
hidden_num_units_1 = 50
hidden_num_units_2 = 50
output_num_units = 10

epochs = 5
batch_size = 128

** Build the network. **

In [30]:
model = models.Sequential()
model.add(layers.Dense(input_num_units, activation='relu'))
model.add(layers.Dense(hidden_num_units_1, activation='relu'))
model.add(layers.Dense(hidden_num_units_2, activation='relu'))
model.add(layers.Dense(output_num_units, activation='softmax'))

** Configure the network. **

In [31]:
model.compile(optimizer='adam',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

** Train the network. **

In [32]:
model.fit(train_images, train_labels, batch_size = 128, epochs = 5, validation_data = (val_images, val_labels))

Train on 42000 samples, validate on 18000 samples
Epoch 1/5
42000/42000 [==============================] - 5s 113us/step - loss: 0.3148 - acc: 0.9066 - val_loss: 0.1536 - val_acc: 0.9543
Epoch 2/5
42000/42000 [==============================] - 4s 100us/step - loss: 0.1164 - acc: 0.9645 - val_loss: 0.1217 - val_acc: 0.9656
Epoch 3/5
42000/42000 [==============================] - 4s 94us/step - loss: 0.0705 - acc: 0.9781 - val_loss: 0.1152 - val_acc: 0.9656
Epoch 4/5
42000/42000 [==============================] - 4s 97us/step - loss: 0.0506 - acc: 0.9845 - val_loss: 0.1065 - val_acc: 0.9696
Epoch 5/5
42000/42000 [==============================] - 4s 98us/step - loss: 0.0375 - acc: 0.9888 - val_loss: 0.0895 - val_acc: 0.9737


Considerations: what can you notice from these results? Is your model performing better than before?

### 3. Dropout

** Define the new variables, remember to define also the dropout_ratio. **

In [33]:
# define vars
input_num_units = 784
hidden_num_units = 50
output_num_units = 10

dropout_ratio = 0.20
epochs = 5
batch_size = 128

** Build the network. **

In [35]:
model = models.Sequential()
model.add(layers.Dense(input_num_units, activation='relu'))
model.add(layers.Dense(hidden_num_units, activation='relu'))
model.add(layers.Dropout(dropout_ratio))
model.add(layers.Dense(output_num_units, activation='softmax'))

** Configure the network. **

In [36]:
model.compile(optimizer='adam',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

** Train the network. **

In [37]:
model.fit(train_images, train_labels, batch_size = 128, epochs = 5, validation_data = (val_images, val_labels))

Train on 42000 samples, validate on 18000 samples
Epoch 1/5
42000/42000 [==============================] - 4s 97us/step - loss: 0.3465 - acc: 0.8983 - val_loss: 0.1697 - val_acc: 0.9500
Epoch 2/5
42000/42000 [==============================] - 4s 87us/step - loss: 0.1353 - acc: 0.9604 - val_loss: 0.1147 - val_acc: 0.9668
Epoch 3/5
42000/42000 [==============================] - 4s 88us/step - loss: 0.0891 - acc: 0.9743 - val_loss: 0.1087 - val_acc: 0.9671
Epoch 4/5
42000/42000 [==============================] - 4s 90us/step - loss: 0.0633 - acc: 0.9810 - val_loss: 0.0949 - val_acc: 0.9726
Epoch 5/5
42000/42000 [==============================] - 4s 86us/step - loss: 0.0489 - acc: 0.9840 - val_loss: 0.0980 - val_acc: 0.9704


Considerations: what can you notice from these results? Is your model improving?

### 4. Increase training Epochs to 50.

This will take a while.

** Define the new variables. **

In [38]:
# define vars
input_num_units = 784
hidden_num_units = 50
output_num_units = 10

dropout_ratio = 0.20
epochs = 50
batch_size = 128

** Build the network. **

In [39]:
model = models.Sequential()
model.add(layers.Dense(input_num_units, activation='relu'))
model.add(layers.Dense(hidden_num_units, activation='relu'))
model.add(layers.Dense(output_num_units, activation='softmax'))

** Configure the network. **

In [40]:
model.compile(optimizer='adam',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

** Train the network. **

In [41]:
model.fit(train_images, train_labels, batch_size = 128, epochs = 50, validation_data = (val_images, val_labels))

Train on 42000 samples, validate on 18000 samples
Epoch 1/50
42000/42000 [==============================] - 4s 96us/step - loss: 0.2882 - acc: 0.9170 - val_loss: 0.1521 - val_acc: 0.9543
Epoch 2/50
42000/42000 [==============================] - 4s 86us/step - loss: 0.1070 - acc: 0.9686 - val_loss: 0.1202 - val_acc: 0.9638
Epoch 3/50
42000/42000 [==============================] - 4s 93us/step - loss: 0.0701 - acc: 0.9782 - val_loss: 0.0949 - val_acc: 0.9719
Epoch 4/50
42000/42000 [==============================] - 4s 93us/step - loss: 0.0422 - acc: 0.9873 - val_loss: 0.0844 - val_acc: 0.9741
Epoch 5/50
42000/42000 [==============================] - 4s 90us/step - loss: 0.0313 - acc: 0.9905 - val_loss: 0.0857 - val_acc: 0.9758
Epoch 6/50
42000/42000 [==============================] - 4s 97us/step - loss: 0.0217 - acc: 0.9938 - val_loss: 0.1007 - val_acc: 0.9730
Epoch 7/50
42000/42000 [==============================] - 4s 90us/step - loss: 0.0179 - acc: 0.9944 - val_loss: 0.0932 - val_acc

Considerations: what can you notice from these results? Has the accuracy increased?

### 5. Make the model "wide" and "deep": more hidden layers, each with more than 50 neurons.

** Define the new variables.**

In [43]:
# define vars
input_num_units = 784
hidden_num_unit_1 = 100
output_num_units = 10

epochs = 25
batch_size = 128

** Build the network. **

In [44]:
model = models.Sequential()
model.add(layers.Dense(input_num_units, activation='relu'))
model.add(layers.Dense(hidden_num_units, activation='relu'))
model.add(layers.Dense(hidden_num_units, activation='relu'))
model.add(layers.Dense(hidden_num_units, activation='relu'))
model.add(layers.Dense(hidden_num_units, activation='relu'))
model.add(layers.Dense(hidden_num_units, activation='relu'))
model.add(layers.Dense(output_num_units, activation='softmax'))

** Configure the network. **

In [45]:
model.compile(optimizer='adam',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

** Train the network. Use 25 epochs if 50 takes too long. **

In [46]:
model.fit(train_images, train_labels, batch_size = 128, epochs = 25, validation_data = (val_images, val_labels))

Train on 42000 samples, validate on 18000 samples
Epoch 1/25
42000/42000 [==============================] - 6s 140us/step - loss: 0.4029 - acc: 0.8723 - val_loss: 0.1659 - val_acc: 0.9498
Epoch 2/25
42000/42000 [==============================] - 5s 116us/step - loss: 0.1337 - acc: 0.9610 - val_loss: 0.1320 - val_acc: 0.9613
Epoch 3/25
42000/42000 [==============================] - 5s 120us/step - loss: 0.0873 - acc: 0.9736 - val_loss: 0.1417 - val_acc: 0.9577
Epoch 4/25
42000/42000 [==============================] - 5s 118us/step - loss: 0.0670 - acc: 0.9791 - val_loss: 0.1304 - val_acc: 0.9621
Epoch 5/25
42000/42000 [==============================] - 5s 123us/step - loss: 0.0491 - acc: 0.9852 - val_loss: 0.1326 - val_acc: 0.9636
Epoch 6/25
42000/42000 [==============================] - 5s 120us/step - loss: 0.0389 - acc: 0.9877 - val_loss: 0.0933 - val_acc: 0.9743
Epoch 7/25
42000/42000 [==============================] - 5s 125us/step - loss: 0.0292 - acc: 0.9913 - val_loss: 0.1039 - 

Considerations: what do you think about your final model?
It seems that we obtained our final solution model. Let's evaluate it with some predictions.

** Make some predictions and Evaluate the network. **

In [47]:
index_2 = model.predict(test_images[:10])

In [48]:
print(test_labels[0:10])

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [49]:
for i in range(0, 10):
    print(np.argmax(index_2[i]))

7
2
1
0
4
1
4
9
6
9


### Hyperparameters Optimization - Grid Search

Instead of proceeding with a "trial and error" approach we can also use GridSearch to combine all the hyperparameters we want to tune, or some of them. What you have to do is to use Sequential() model in Keras as a part of the Scikit-Learn workflow via the wrappers. 
Check out how this workflow works.


Please note that without GPU is extremely time consuming to tune all the hyperparameters in one shoot, by using an appropriate number of epochs. For this reason, in this example the idea is for you to understand how you can use GridSerach with Keras Model, but you will probably not be able to obtain an excellent model.

For this reason, try to tune the number of neurons in the hidden layers (more than one hidden layer) with just 5-10 epochs.

** Import GridSearchCV and KerasClassifier.**

In [5]:
from sklearn.model_selection import GridSearchCV
from keras.wrappers.scikit_learn import KerasClassifier


In [6]:
input_num_units = 784
hidden_num_unit = 100
output_num_units = 10

** Create a function called `create_model` in which you build your KerasClassifier with number of hidden units equal to a general variable (you can call this `neurons`). Inside the function you should then also compile the model.**

In [9]:
def create_model(neurons):
    model = models.Sequential()
    model.add(layers.Dense(input_num_units, activation='relu'))
    model.add(layers.Dense(neurons, activation='relu'))
    model.add(layers.Dense(neurons, activation='relu'))
    model.add(layers.Dense(neurons, activation='relu'))
    model.add(layers.Dense(neurons, activation='relu'))
    model.add(layers.Dense(neurons, activation='relu'))
    model.add(layers.Dense(output_num_units, activation='softmax'))
    model.compile(optimizer='adam',
                loss='categorical_crossentropy',
                metrics=['accuracy'])
    


** Create a model wrapper.**

In [11]:
my_classifier = KerasClassifier(create_model)

** Create a dictionary of parameters grid for the number of neurons in the hidden layer.**

In [ ]:
 param_grid={'dense_layer_sizes': dense_size_candidates,
                                     # epochs is avail for tuning even when not
                                     # an argument to model building function
                                     'epochs': [5, 10],
                                     'filters': [8],
                                     'kernel_size': [3],
                                     'pool_size': [2]}

** Grid Search: use `GridSearchCV`with the model you have obtained from the wrapper as estimator and the dictionary you have just created as param_grid.**

** Fit the result from the Grid Search, call your result `grid_result`. **

** Let's print some results. Fill in the #TO DOs with the best_score and best_params that you got after fitting. **

In [ ]:
print("Best: %f using %s" % (#TO DO: take the best score, #TO DO: take the best parameters) 
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))
    